### ISSUE TITLE
Incorrect path for visual studio runtime library functions

### ISSUE THREAD

**Issue by pgalkin** [x13pixels/remedybg-issues#261] opened 2022-07-24 08:34 UTC
I created an empty program with just `WinMain()` in it. Compiled it with
```
cl -Zi main.cpp
```
and launched the debugger
```
remedybg main.exe
```
In the call stack right before the `WinMain()` there is a call to `__scrt_common_main_seh()`. Clicking on it tries to find the source file in
```
[7/24/2022 12:22:30 PM] Unable to open D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl. File not found.
```
Here's a screenshot

![remedy_unable_to_find](https://user-images.githubusercontent.com/7285838/180638706-f93ea69a-446c-49c2-a07a-9d15a26408b5.PNG)

The `D:\a\_work\` part seems suspicious, as if it's been hardcoded. I fixed it by creating the whole directory structure and copying the contents of
```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\crt\src\vcruntime\
```
in there.

![vcruntime_dir](https://user-images.githubusercontent.com/7285838/180638878-a52c46a4-3924-4106-87ed-3e643e4e37f3.PNG)

![remedy_crt_found](https://user-images.githubusercontent.com/7285838/180638947-55ae9433-1168-49fd-9f0c-91704f3623f2.PNG)

But I think it should look for the file in another place.

**Comment by x13pixels** [comment] 2022-07-29 00:28
The source paths are the ones baked into the Microsoft PDBs. Will need to support additional source paths. Closing as duplicate of #201

**Closed as completed by x13pixels** 2022-07-29 00:28 UTC
Labels: Type: Duplicate
