### ISSUE TITLE
0.3.1 Crash when typing under Application and Parameters tab

### ISSUE THREAD

**Issue by aelthalyste** [x13pixels/remedybg-issues#190] opened 2020-11-04 15:33 UTC
To reproduce, just open remedybg(without loading any session at all just download and open 0.3.1.0), try to type anything under Application and Parameters tab.

Reproducible one :
- If you try to type anything in environment tab, it just crashes.

Mostly crashing :
- When typing to "Command" or "Working Directory", it mostly crashes.

**Comment by x13pixels** [comment] 2020-11-04 23:21
Duplicate of #184. Fixed for 0.3.1.1 release.

**Closed as completed by x13pixels** 2020-11-04 23:21 UTC
Labels: Type: Duplicate
