### ISSUE TITLE
MSVC Address sanitizer is not compatible with remedybg

### ISSUE THREAD

**Issue by aelthalyste** [x13pixels/remedybg-issues#209] opened 2021-03-11 15:12 UTC
Looks like we can't use remedy with adress sanitizer. It won't even start debugging. If you compile with these flags and step into program with F10, it raises exception. It runs fine with visual studio(see version below) 

to reproduce: Compile any program with /fsanitize=adress and try to step in. I'm going to post all of my compiler flags in case something wrong about them.

Compiler : MSVC 19.28.29910
Compiler flags: /EHsc /W0 /fsanitize=address /DEBUG:FULL /Zi /FC /Od /Fa /INCREMENTAL:NO /F 16777216

![resim](https://user-images.githubusercontent.com/31110771/110808090-bd70f780-8294-11eb-8377-3023729ceeca.png)
Dissassembler:
![resim](https://user-images.githubusercontent.com/31110771/110808246-d9749900-8294-11eb-97c1-39d2a28c75b8.png)

code: not important, i tried bunch of things and all failed similiarly

**Comment by x13pixels** [comment] 2021-03-11 17:10
#197 (Clang's Address Sanitizer currently incompatible with remedybg) is slated to be fixed in the next release. I'm guessing this will be similar and can take a look, then. Thanks!

**Comment by x13pixels** [comment] 2021-03-20 21:51
Verified that is a duplicate of #197 slated to be fixed in 0.3.5.0.

**Closed as completed by x13pixels** 2021-03-20 21:51 UTC
Labels: Type: Duplicate
