### ISSUE TITLE
It is not possible to step out of a function that was just stepped into

### ISSUE THREAD

**Issue by Aerek-Yasa** [x13pixels/remedybg-issues#297] opened 2024-01-14 05:02 UTC
Observed behaviour: When stepping into a function and then immediately stepping out, nothing happens. The debugger also no longer indicates what line it is current at with a yellow arrow. Performing another step fixes the issue making it possible to use step out.

Expected behaviour: It is expected that RemedyBG steps out of the function it just stepped into.

Here is a GIF showing the observed behaviour and reproduction steps:
![ezgif-1-befa9c4b12](https://github.com/x13pixels/remedybg-issues/assets/88772708/ff33f6f9-72fc-4f3f-884a-716e635fb92e)

RemedyBG Version: 0.3.9.7

~Aerek

**Comment by x13pixels** [comment] 2024-01-14 13:32
I'm unable to reproduce this with MSCV (`cl /Z7 program.c`) or Clang (`clang-cl /Z7 program.c`). Could you please include what compiler is being used and its arguments? Thanks!

**Comment by Aerek-Yasa** [comment] 2024-01-14 18:21
The bug was reproduced several times yesterday. Today the bug is no longer reproducible. 
The compiler that was used at the time was MSVC 2022.

cl.exe version: C/C++ Optimizing Compiler Version 19.37.32824 for x64
link.exe version: Incremental Linker Version 14.37.32824.0

The command that was used to create the program was `cl program.c /Zi`

~Aerek

**Comment by x13pixels** [comment] 2024-01-28 21:12
Wondering if this was with an older version of RemedyBG by chance? There was a bug fixed in 0.3.9.5 that is possibly related to this.

In any case, I beefed up some test code to hammer on this specific test case as well testing via the RemedyBG driver and was still unable to reproduce the problem. If nothing else, the report served as an impetus to improve some testing capabilities so thank you!

Closing this but will continue to test the provided sample along with any future changes.

**Closed as completed by x13pixels** 2024-01-28 21:12 UTC
Labels: Type: Bug, Priority: 4 (Medium)
