### ISSUE TITLE
Text highlighting in source files is offset from cursor

### ISSUE THREAD

**Issue by sir-pinecone** [x13pixels/remedybg-issues#99] opened 2019-04-18 20:32 UTC
I'm using 0.2.1 on Win 7. Text highlighting isn't starting at the mouse cursor. 

![bug](https://user-images.githubusercontent.com/40753/56389379-66bd2900-61f7-11e9-98cf-23edc0112bd8.gif)

**Comment by x13pixels** [comment] 2019-04-18 20:46
Duplicate of #94.

**Closed as completed by x13pixels** 2019-04-18 20:46 UTC
Labels: Type: Duplicate
