### ISSUE TITLE
Breakpoints in Disassembly Window

### ISSUE THREAD

**Issue by LowySt** [x13pixels/remedybg-issues#105] opened 2019-04-28 13:00 UTC
It should be possible to set a breakpoint in the disassembly window. I have mixed asm/c code and If i have to debug some assembly it is necessary to be able to set breakpoints in the disasm.

**Comment by x13pixels** [comment] 2019-04-28 16:12
Duplicate of #50. This is being working for the next release.

**Closed as completed by x13pixels** 2019-04-28 16:12 UTC
Labels: Type: Duplicate
