### ISSUE TITLE
Need "set next statement" in both source and disasm windows

### ISSUE THREAD

**Issue by cmuratori** [x13pixels/remedybg-issues#82] opened 2019-04-14 23:21 UTC
One of the things I use frequently when debugging is the ability to set the IP somewhere after the current line, to skip over something that is broken.  "Set next statement" should be available in the right-click menu for both the source and disasm windows, and it is just a basic "set the IP to the start of this line's code".  It's really handy!

\- Casey

**Comment by x13pixels** [comment] 2019-04-15 02:37
Duplicate of #20

**Closed as completed by x13pixels** 2019-04-15 02:37 UTC
Labels: Type: Duplicate
