### ISSUE TITLE
Add symbol/function suggestion in the "New Function Breakpoint" window

### ISSUE THREAD

**Issue by direbroom** [x13pixels/remedybg-issues#98] opened 2019-04-17 22:21 UTC
While this is not the most important thing in a small codebase or a codebase that you own 100%, it's very useful in large project with multiple people if you don't know the exact name of everything but have a rough idea and want to break there... well autocomplete :) thanks!

**Comment by x13pixels** [comment] 2019-04-18 21:55
Duplicate of #48

**Closed as completed by x13pixels** 2019-04-18 21:55 UTC
Labels: Type: Duplicate
